workflows:
  testFlight:
    name: "Ios Release"
    integrations:
      app_store_connect: Ayoub Es-sedraouy

    environment:
      flutter: 3.41.0
      ios_signing:
        distribution_type: app_store
        provisioning_profiles:
          - provisioning_3uTools-Tips
        certificates:
          - Certificate_ayoub

    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Fix extension entitlements paths after use-profiles
        script: bash ios/scripts/fix_extension_signing_paths.sh ios/Runner.xcodeproj/project.pbxproj

      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - zouhiramix50@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration